/* DO NOT EDIT - AUTOGENERATED */
/**
 * 				NativeBass Project
 *
 * Want to use BASS (www.un4seen.com) in the Java language ? NativeBass is made for you.
 * Copyright @ 2007-2011 Jérôme Jouvie
 *
 * Created on 02 jul. 2007
 * @version file v1.1.1
 * @author Jérôme Jouvie (Jouvieje)
 * @site   http://jerome.jouvie.free.fr/
 * @mail   jerome.jouvie@gmail.com
 * 
 * 
 * INTRODUCTION
 * BASS is an audio library for use in Windows and Mac OSX software.
 * Its purpose is to provide developers with the most powerful and
 * efficient (yet easy to use), sample, stream (MP3, MP2, MP1, OGG, WAV, AIFF,
 * custom generated, and more via add-ons), MOD music (XM, IT, S3M, MOD, MTM, UMX),
 * MO3 music (MP3/OGG compressed MODs),
 * and recording functions. All in a tiny DLL, under 100KB* in size.
 * 
 * BASS official web site :
 * 		http://www.un4seen.com/
 * 
 * 
 * GNU LESSER GENERAL PUBLIC LICENSE
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of the License,
 * or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the
 * Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307 USA 
 */

package jouvieje.bass.defines;

/**
 * BASS_ChannelGetTags types : what's returned [NAME] BASS_TAG
 */
public interface BASS_TAG {
	/** ID3v1 tags : TAG_ID3 structure */
	public static final int BASS_TAG_ID3 = 0;
	/** ID3v2 tags : variable length block */
	public static final int BASS_TAG_ID3V2 = 1;
	/** OGG comments : series of null-terminated UTF-8 strings */
	public static final int BASS_TAG_OGG = 2;
	/** HTTP headers : series of null-terminated ANSI strings */
	public static final int BASS_TAG_HTTP = 3;
	/** ICY headers : series of null-terminated ANSI strings */
	public static final int BASS_TAG_ICY = 4;
	/** ICY metadata : ANSI string */
	public static final int BASS_TAG_META = 5;
	/** APE tags */
	public static final int BASS_TAG_APE = 6;
	/** iTunes/MP4 metadata */
	public static final int BASS_TAG_MP4 = 7;
	/** OGG encoder : UTF-8 string */
	public static final int BASS_TAG_VENDOR = 9;
	/** Lyric3v2 tag : ASCII string */
	public static final int BASS_TAG_LYRICS3 = 10;
	/** CoreAudio codec info : TAG_CA_CODEC structure */
	public static final int BASS_TAG_CA_CODEC = 11;
	/** Media Foundation tags : series of null-terminated UTF-8 strings */
	public static final int BASS_TAG_MF = 13;
	/** WAVE format : WAVEFORMATEEX structure */
	public static final int BASS_TAG_WAVEFORMAT = 14;
	/** RIFF "INFO" tags : series of null-terminated ANSI strings */
	public static final int BASS_TAG_RIFF_INFO = 0x100;
	/** RIFF/BWF "bext" tags : TAG_BEXT structure */
	public static final int BASS_TAG_RIFF_BEXT = 0x101;
	/** RIFF/BWF "cart" tags : TAG_CART structure */
	public static final int BASS_TAG_RIFF_CART = 0x102;
	/** RIFF "DISP" text tag : ANSI string */
	public static final int BASS_TAG_RIFF_DISP = 0x103;
	/** + index #, binary APE tag : TAG_APE_BINARY structure */
	public static final int BASS_TAG_APE_BINARY = 0x1000;
	/** MOD music name : ANSI string */
	public static final int BASS_TAG_MUSIC_NAME = 0x10000;
	/** MOD message : ANSI string */
	public static final int BASS_TAG_MUSIC_MESSAGE = 0x10001;
	/** MOD order list : BYTE array of pattern numbers */
	public static final int BASS_TAG_MUSIC_ORDERS = 0x10002;
	/** + instrument #, MOD instrument name : ANSI string */
	public static final int BASS_TAG_MUSIC_INST = 0x10100;
	/** + sample #, MOD sample name : ANSI string */
	public static final int BASS_TAG_MUSIC_SAMPLE = 0x10300;
	/** cuesheet : TAG_FLAC_CUE structure */
	public static final int BASS_TAG_FLAC_CUE = 12;
	/** + index #, picture : TAG_FLAC_PICTURE structure */
	public static final int BASS_TAG_FLAC_PICTURE = 0x12000;
	/** + track #, track text : array of null-terminated ANSI strings */
	public static final int BASS_TAG_MIDI_TRACK = 0x11000;
}