/* DO NOT EDIT - AUTOGENERATED */
/**
 * 				NativeBass Project
 *
 * Want to use BASS (www.un4seen.com) in the Java language ? NativeBass is made for you.
 * Copyright © 2007-2011 Jérôme JOUVIE
 *
 * Created on 02 jul. 2007
 * @version file v1.1.1
 * @author Jérôme JOUVIE (Jouvieje)
 * @site   http://jerome.jouvie.free.fr/
 * @mail   jerome.jouvie@gmail.com
 * 
 * 
 * INTRODUCTION
 * BASS is an audio library for use in Windows and Mac OSX software.
 * Its purpose is to provide developers with the most powerful and
 * efficient (yet easy to use), sample, stream (MP3, MP2, MP1, OGG, WAV, AIFF,
 * custom generated, and more via add-ons), MOD music (XM, IT, S3M, MOD, MTM, UMX),
 * MO3 music (MP3/OGG compressed MODs),
 * and recording functions. All in a tiny DLL, under 100KB* in size.
 * 
 * BASS official web site :
 * 		http://www.un4seen.com/
 * 
 * 
 * GNU LESSER GENERAL PUBLIC LICENSE
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of the License,
 * or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the
 * Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307 USA 
 */

#include "NativeBass.h"
#include "bass.h"
#include "bassenc.h"
#include "bassflac.h"
#include "bassmidi.h"
#include "bassmix.h"
#include "basswv.h"
#include "bass_aac.h"
#include "bass_ac3.h"
#include "bass_alac.h"
#include "bass_fx.h"
#include "bass_mpc.h"
#include "bass_spx.h"
#include "Utils.h"
#include "Pointer.h"
#include "JavaObject.h"
#include "jouvieje_bass_structures_StructureJNI.h"
#include "CallbackManager.h"

JNIEXPORT jlong JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONT_1new(JNIEnv *java_env, jclass jcls) {
	BASS_MIDI_FONT *result_ = new BASS_MIDI_FONT();
	CheckAllocation(java_env, result_);
	N2J_PTR2ADR(jresult, result_, BASS_MIDI_FONT *);
	return jresult;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONT_1delete(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_MIDI_FONT *pointer = N2J_CAST(jpointer, BASS_MIDI_FONT *);
	delete pointer;
}

JNIEXPORT jlong JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONT_1get_1font(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_MIDI_FONT *pointer = N2J_CAST(jpointer, BASS_MIDI_FONT *);
	HSOUNDFONT cresult = pointer->font;
	jlong jresult = N2J_CAST(cresult, jlong);
	return jresult;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONT_1set_1font(JNIEnv *java_env, jclass jcls, jlong jpointer, jlong jfont) {
	BASS_MIDI_FONT *pointer = N2J_CAST(jpointer, BASS_MIDI_FONT *);
	HSOUNDFONT cresult = N2J_CAST(jfont, HSOUNDFONT);
	pointer->font = cresult;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONT_1get_1preset(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_MIDI_FONT *pointer = N2J_CAST(jpointer, BASS_MIDI_FONT *);
	int result_ = pointer->preset;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONT_1set_1preset(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jpreset) {
	BASS_MIDI_FONT *pointer = N2J_CAST(jpointer, BASS_MIDI_FONT *);
	int preset = (int)jpreset;
	pointer->preset = preset;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONT_1get_1bank(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_MIDI_FONT *pointer = N2J_CAST(jpointer, BASS_MIDI_FONT *);
	int result_ = pointer->bank;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONT_1set_1bank(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jbank) {
	BASS_MIDI_FONT *pointer = N2J_CAST(jpointer, BASS_MIDI_FONT *);
	int bank = (int)jbank;
	pointer->bank = bank;
}



