/* DO NOT EDIT - AUTOGENERATED */
/**
 * 				NativeBass Project
 *
 * Want to use BASS (www.un4seen.com) in the Java language ? NativeBass is made for you.
 * Copyright © 2007-2011 Jérôme JOUVIE
 *
 * Created on 02 jul. 2007
 * @version file v1.1.1
 * @author Jérôme JOUVIE (Jouvieje)
 * @site   http://jerome.jouvie.free.fr/
 * @mail   jerome.jouvie@gmail.com
 * 
 * 
 * INTRODUCTION
 * BASS is an audio library for use in Windows and Mac OSX software.
 * Its purpose is to provide developers with the most powerful and
 * efficient (yet easy to use), sample, stream (MP3, MP2, MP1, OGG, WAV, AIFF,
 * custom generated, and more via add-ons), MOD music (XM, IT, S3M, MOD, MTM, UMX),
 * MO3 music (MP3/OGG compressed MODs),
 * and recording functions. All in a tiny DLL, under 100KB* in size.
 * 
 * BASS official web site :
 * 		http://www.un4seen.com/
 * 
 * 
 * GNU LESSER GENERAL PUBLIC LICENSE
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of the License,
 * or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the
 * Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307 USA 
 */

#include "NativeBass.h"
#include "bass.h"
#include "bassenc.h"
#include "bassflac.h"
#include "bassmidi.h"
#include "bassmix.h"
#include "basswv.h"
#include "bass_aac.h"
#include "bass_ac3.h"
#include "bass_alac.h"
#include "bass_fx.h"
#include "bass_mpc.h"
#include "bass_spx.h"
#include "Utils.h"
#include "Pointer.h"
#include "JavaObject.h"
#include "jouvieje_bass_structures_StructureJNI.h"
#include "CallbackManager.h"

JNIEXPORT jlong JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1new(JNIEnv *java_env, jclass jcls) {
	BASS_BFX_CHORUS *result_ = new BASS_BFX_CHORUS();
	CheckAllocation(java_env, result_);
	N2J_PTR2ADR(jresult, result_, BASS_BFX_CHORUS *);
	return jresult;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1delete(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	delete pointer;
}

JNIEXPORT jfloat JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1get_1fDryMix(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	float result_ = pointer->fDryMix;
	return (jfloat)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1set_1fDryMix(JNIEnv *java_env, jclass jcls, jlong jpointer, jfloat jfDryMix) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	float fDryMix = (float)jfDryMix;
	pointer->fDryMix = fDryMix;
}

JNIEXPORT jfloat JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1get_1fWetMix(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	float result_ = pointer->fWetMix;
	return (jfloat)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1set_1fWetMix(JNIEnv *java_env, jclass jcls, jlong jpointer, jfloat jfWetMix) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	float fWetMix = (float)jfWetMix;
	pointer->fWetMix = fWetMix;
}

JNIEXPORT jfloat JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1get_1fFeedback(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	float result_ = pointer->fFeedback;
	return (jfloat)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1set_1fFeedback(JNIEnv *java_env, jclass jcls, jlong jpointer, jfloat jfFeedback) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	float fFeedback = (float)jfFeedback;
	pointer->fFeedback = fFeedback;
}

JNIEXPORT jfloat JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1get_1fMinSweep(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	float result_ = pointer->fMinSweep;
	return (jfloat)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1set_1fMinSweep(JNIEnv *java_env, jclass jcls, jlong jpointer, jfloat jfMinSweep) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	float fMinSweep = (float)jfMinSweep;
	pointer->fMinSweep = fMinSweep;
}

JNIEXPORT jfloat JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1get_1fMaxSweep(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	float result_ = pointer->fMaxSweep;
	return (jfloat)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1set_1fMaxSweep(JNIEnv *java_env, jclass jcls, jlong jpointer, jfloat jfMaxSweep) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	float fMaxSweep = (float)jfMaxSweep;
	pointer->fMaxSweep = fMaxSweep;
}

JNIEXPORT jfloat JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1get_1fRate(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	float result_ = pointer->fRate;
	return (jfloat)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1set_1fRate(JNIEnv *java_env, jclass jcls, jlong jpointer, jfloat jfRate) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	float fRate = (float)jfRate;
	pointer->fRate = fRate;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1get_1lChannel(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	int result_ = pointer->lChannel;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1BFX_1CHORUS_1set_1lChannel(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jlChannel) {
	BASS_BFX_CHORUS *pointer = N2J_CAST(jpointer, BASS_BFX_CHORUS *);
	int lChannel = (int)jlChannel;
	pointer->lChannel = lChannel;
}



