/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jouvieje_bass_enumerations_EnumerationJNI */

#ifndef _Included_jouvieje_bass_enumerations_EnumerationJNI
#define _Included_jouvieje_bass_enumerations_EnumerationJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_ATTRIB_TEMPO_PITCH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1ATTRIB_1TEMPO_1PITCH
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_ATTRIB_TEMPO_FREQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1ATTRIB_1TEMPO_1FREQ
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_ATTRIB_TEMPO_OPTION_AA_FILTER_LENGTH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1ATTRIB_1TEMPO_1OPTION_1AA_1FILTER_1LENGTH
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_ATTRIB_TEMPO_OPTION_USE_QUICKALGO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1ATTRIB_1TEMPO_1OPTION_1USE_1QUICKALGO
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_ATTRIB_TEMPO_OPTION_SEQUENCE_MS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1ATTRIB_1TEMPO_1OPTION_1SEQUENCE_1MS
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_ATTRIB_TEMPO_OPTION_SEEKWINDOW_MS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1ATTRIB_1TEMPO_1OPTION_1SEEKWINDOW_1MS
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_ATTRIB_TEMPO_OPTION_OVERLAP_MS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1ATTRIB_1TEMPO_1OPTION_1OVERLAP_1MS
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_ATTRIB_TEMPO_OPTION_PREVENT_CLICK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1ATTRIB_1TEMPO_1OPTION_1PREVENT_1CLICK
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_BFX_BQF_LOWPASS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1BFX_1BQF_1LOWPASS
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_BFX_BQF_HIGHPASS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1BFX_1BQF_1HIGHPASS
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_BFX_BQF_BANDPASS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1BFX_1BQF_1BANDPASS
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_BFX_BQF_BANDPASS_Q
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1BFX_1BQF_1BANDPASS_1Q
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_BFX_BQF_NOTCH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1BFX_1BQF_1NOTCH
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_BFX_BQF_ALLPASS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1BFX_1BQF_1ALLPASS
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_BFX_BQF_PEAKINGEQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1BFX_1BQF_1PEAKINGEQ
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_BFX_BQF_LOWSHELF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1BFX_1BQF_1LOWSHELF
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_BFX_BQF_HIGHSHELF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1BFX_1BQF_1HIGHSHELF
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_ECHO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1ECHO
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_FLANGER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1FLANGER
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_VOLUME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1VOLUME
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_PEAKEQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1PEAKEQ
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_REVERB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1REVERB
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_LPF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1LPF
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_MIX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1MIX
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_DAMP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1DAMP
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_AUTOWAH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1AUTOWAH
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_ECHO2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1ECHO2
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_PHASER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1PHASER
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_ECHO3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1ECHO3
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_CHORUS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1CHORUS
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_APF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1APF
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_COMPRESSOR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1COMPRESSOR
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_DISTORTION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1DISTORTION
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_COMPRESSOR2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1COMPRESSOR2
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_VOLUME_ENV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1VOLUME_1ENV
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BFX_BQF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BFX_1BQF
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BPM_TRAN_X2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BPM_1TRAN_1X2
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BPM_TRAN_2FREQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BPM_1TRAN_12FREQ
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BPM_TRAN_FREQ2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BPM_1TRAN_1FREQ2
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BPM_TRAN_2PERCENT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BPM_1TRAN_12PERCENT
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_BASS_FX_BPM_TRAN_PERCENT2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1BASS_1FX_1BPM_1TRAN_1PERCENT2
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_GENERIC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1GENERIC
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_PADDEDCELL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1PADDEDCELL
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_ROOM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1ROOM
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_BATHROOM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1BATHROOM
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_LIVINGROOM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1LIVINGROOM
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_STONEROOM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1STONEROOM
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_AUDITORIUM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1AUDITORIUM
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_CONCERTHALL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1CONCERTHALL
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_CAVE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1CAVE
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_ARENA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1ARENA
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_HANGAR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1HANGAR
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_CARPETEDHALLWAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1CARPETEDHALLWAY
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_HALLWAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1HALLWAY
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_STONECORRIDOR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1STONECORRIDOR
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_ALLEY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1ALLEY
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_FOREST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1FOREST
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_CITY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1CITY
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_MOUNTAINS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1MOUNTAINS
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_QUARRY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1QUARRY
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_PLAIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1PLAIN
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_PARKINGLOT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1PARKINGLOT
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_SEWERPIPE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1SEWERPIPE
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_UNDERWATER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1UNDERWATER
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_DRUGGED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1DRUGGED
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_DIZZY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1DIZZY
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_PSYCHOTIC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1PSYCHOTIC
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_EAX_ENVIRONMENT_COUNT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1EAX_1ENVIRONMENT_1COUNT
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_STREAMPROC_DUMMY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1STREAMPROC_1DUMMY
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_enumerations_EnumerationJNI
 * Method:    get_STREAMPROC_PUSH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_enumerations_EnumerationJNI_get_1STREAMPROC_1PUSH
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
