/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jouvieje_bass_BassInit */

#ifndef _Included_jouvieje_bass_BassInit
#define _Included_jouvieje_bass_BassInit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jouvieje_bass_BassInit
 * Method:    attachJavaVM
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jouvieje_bass_BassInit_attachJavaVM
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_BassInit
 * Method:    get_BASSVERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_BassInit_get_1BASSVERSION
  (JNIEnv *, jclass);

/*
 * Class:     jouvieje_bass_BassInit
 * Method:    get_NATIVEBASS_VERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jouvieje_bass_BassInit_get_1NATIVEBASS_1VERSION
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
