/* DO NOT EDIT - AUTOGENERATED */
/**
 * 				NativeBass Project
 *
 * Want to use BASS (www.un4seen.com) in the Java language ? NativeBass is made for you.
 * Copyright © 2007-2011 Jérôme JOUVIE
 *
 * Created on 02 jul. 2007
 * @version file v1.1.1
 * @author Jérôme JOUVIE (Jouvieje)
 * @site   http://jerome.jouvie.free.fr/
 * @mail   jerome.jouvie@gmail.com
 * 
 * 
 * INTRODUCTION
 * BASS is an audio library for use in Windows and Mac OSX software.
 * Its purpose is to provide developers with the most powerful and
 * efficient (yet easy to use), sample, stream (MP3, MP2, MP1, OGG, WAV, AIFF,
 * custom generated, and more via add-ons), MOD music (XM, IT, S3M, MOD, MTM, UMX),
 * MO3 music (MP3/OGG compressed MODs),
 * and recording functions. All in a tiny DLL, under 100KB* in size.
 * 
 * BASS official web site :
 * 		http://www.un4seen.com/
 * 
 * 
 * GNU LESSER GENERAL PUBLIC LICENSE
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of the License,
 * or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the
 * Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307 USA 
 */

#include "NativeBass.h"
#include "bass.h"
#include "bassenc.h"
#include "bassflac.h"
#include "bassmidi.h"
#include "bassmix.h"
#include "basswv.h"
#include "bass_aac.h"
#include "bass_ac3.h"
#include "bass_alac.h"
#include "bass_fx.h"
#include "bass_mpc.h"
#include "bass_spx.h"
#include "Utils.h"
#include "Pointer.h"
#include "JavaObject.h"
#include "jouvieje_bass_structures_StructureJNI.h"
#include "CallbackManager.h"

JNIEXPORT jlong JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1new(JNIEnv *java_env, jclass jcls) {
	BASS_MIDI_FONTINFO *result_ = new BASS_MIDI_FONTINFO();
	CheckAllocation(java_env, result_);
	N2J_PTR2ADR(jresult, result_, BASS_MIDI_FONTINFO *);
	return jresult;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1delete(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	delete pointer;
}

JNIEXPORT jstring JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1get_1name(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	const char *result_ = N2J_CAST(pointer->name, const char *);
	jstring jresult = 0;
	if(result_) {
		jresult = java_env->NewStringUTF((const char *)result_);
	}
	return jresult;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1set_1name(JNIEnv *java_env, jclass jcls, jlong jpointer, jbyteArray jname) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	const char *name = 0;
	if(jname) {
		name = (const char *)getByteArrayElements(java_env, jname);
		pointer->name = name;
	}
	else {
		pointer->name = (const char *)0;
	}
}

JNIEXPORT jstring JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1get_1copyright(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	const char *result_ = N2J_CAST(pointer->copyright, const char *);
	jstring jresult = 0;
	if(result_) {
		jresult = java_env->NewStringUTF((const char *)result_);
	}
	return jresult;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1set_1copyright(JNIEnv *java_env, jclass jcls, jlong jpointer, jbyteArray jcopyright) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	const char *copyright = 0;
	if(jcopyright) {
		copyright = (const char *)getByteArrayElements(java_env, jcopyright);
		pointer->copyright = copyright;
	}
	else {
		pointer->copyright = (const char *)0;
	}
}

JNIEXPORT jstring JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1get_1comment(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	const char *result_ = N2J_CAST(pointer->comment, const char *);
	jstring jresult = 0;
	if(result_) {
		jresult = java_env->NewStringUTF((const char *)result_);
	}
	return jresult;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1set_1comment(JNIEnv *java_env, jclass jcls, jlong jpointer, jbyteArray jcomment) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	const char *comment = 0;
	if(jcomment) {
		comment = (const char *)getByteArrayElements(java_env, jcomment);
		pointer->comment = comment;
	}
	else {
		pointer->comment = (const char *)0;
	}
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1get_1presets(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	DWORD result_ = pointer->presets;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1set_1presets(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jpresets) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	DWORD presets = (DWORD)jpresets;
	pointer->presets = presets;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1get_1samsize(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	DWORD result_ = pointer->samsize;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1set_1samsize(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jsamsize) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	DWORD samsize = (DWORD)jsamsize;
	pointer->samsize = samsize;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1get_1samload(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	DWORD result_ = pointer->samload;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1set_1samload(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jsamload) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	DWORD samload = (DWORD)jsamload;
	pointer->samload = samload;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1get_1samtype(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	DWORD result_ = pointer->samtype;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1MIDI_1FONTINFO_1set_1samtype(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jsamtype) {
	BASS_MIDI_FONTINFO *pointer = N2J_CAST(jpointer, BASS_MIDI_FONTINFO *);
	DWORD samtype = (DWORD)jsamtype;
	pointer->samtype = samtype;
}



