/* DO NOT EDIT - AUTOGENERATED */
/**
 * 				NativeBass Project
 *
 * Want to use BASS (www.un4seen.com) in the Java language ? NativeBass is made for you.
 * Copyright © 2007-2011 Jérôme JOUVIE
 *
 * Created on 02 jul. 2007
 * @version file v1.1.1
 * @author Jérôme JOUVIE (Jouvieje)
 * @site   http://jerome.jouvie.free.fr/
 * @mail   jerome.jouvie@gmail.com
 * 
 * 
 * INTRODUCTION
 * BASS is an audio library for use in Windows and Mac OSX software.
 * Its purpose is to provide developers with the most powerful and
 * efficient (yet easy to use), sample, stream (MP3, MP2, MP1, OGG, WAV, AIFF,
 * custom generated, and more via add-ons), MOD music (XM, IT, S3M, MOD, MTM, UMX),
 * MO3 music (MP3/OGG compressed MODs),
 * and recording functions. All in a tiny DLL, under 100KB* in size.
 * 
 * BASS official web site :
 * 		http://www.un4seen.com/
 * 
 * 
 * GNU LESSER GENERAL PUBLIC LICENSE
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of the License,
 * or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the
 * Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307 USA 
 */

#include "NativeBass.h"
#include "bass.h"
#include "bassenc.h"
#include "bassflac.h"
#include "bassmidi.h"
#include "bassmix.h"
#include "basswv.h"
#include "bass_aac.h"
#include "bass_ac3.h"
#include "bass_alac.h"
#include "bass_fx.h"
#include "bass_mpc.h"
#include "bass_spx.h"
#include "Utils.h"
#include "Pointer.h"
#include "JavaObject.h"
#include "jouvieje_bass_structures_StructureJNI.h"
#include "CallbackManager.h"

JNIEXPORT jlong JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1new(JNIEnv *java_env, jclass jcls) {
	BASS_SAMPLE *result_ = new BASS_SAMPLE();
	CheckAllocation(java_env, result_);
	N2J_PTR2ADR(jresult, result_, BASS_SAMPLE *);
	return jresult;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1delete(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	delete pointer;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1freq(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD result_ = pointer->freq;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1freq(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jfreq) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD freq = (DWORD)jfreq;
	pointer->freq = freq;
}

JNIEXPORT jfloat JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1volume(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	float result_ = pointer->volume;
	return (jfloat)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1volume(JNIEnv *java_env, jclass jcls, jlong jpointer, jfloat jvolume) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	float volume = (float)jvolume;
	pointer->volume = volume;
}

JNIEXPORT jfloat JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1pan(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	float result_ = pointer->pan;
	return (jfloat)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1pan(JNIEnv *java_env, jclass jcls, jlong jpointer, jfloat jpan) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	float pan = (float)jpan;
	pointer->pan = pan;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1flags(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD result_ = pointer->flags;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1flags(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jflags) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD flags = (DWORD)jflags;
	pointer->flags = flags;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1length(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD result_ = pointer->length;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1length(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jlength) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD length = (DWORD)jlength;
	pointer->length = length;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1max(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD result_ = pointer->max;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1max(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jmax) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD max = (DWORD)jmax;
	pointer->max = max;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1origres(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD result_ = pointer->origres;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1origres(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jorigres) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD origres = (DWORD)jorigres;
	pointer->origres = origres;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1chans(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD result_ = pointer->chans;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1chans(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jchans) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD chans = (DWORD)jchans;
	pointer->chans = chans;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1mingap(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD result_ = pointer->mingap;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1mingap(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jmingap) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD mingap = (DWORD)jmingap;
	pointer->mingap = mingap;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1mode3d(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD result_ = pointer->mode3d;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1mode3d(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jmode3d) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD mode3d = (DWORD)jmode3d;
	pointer->mode3d = mode3d;
}

JNIEXPORT jfloat JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1mindist(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	float result_ = pointer->mindist;
	return (jfloat)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1mindist(JNIEnv *java_env, jclass jcls, jlong jpointer, jfloat jmindist) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	float mindist = (float)jmindist;
	pointer->mindist = mindist;
}

JNIEXPORT jfloat JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1maxdist(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	float result_ = pointer->maxdist;
	return (jfloat)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1maxdist(JNIEnv *java_env, jclass jcls, jlong jpointer, jfloat jmaxdist) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	float maxdist = (float)jmaxdist;
	pointer->maxdist = maxdist;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1iangle(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD result_ = pointer->iangle;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1iangle(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jiangle) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD iangle = (DWORD)jiangle;
	pointer->iangle = iangle;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1oangle(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD result_ = pointer->oangle;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1oangle(JNIEnv *java_env, jclass jcls, jlong jpointer, jint joangle) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD oangle = (DWORD)joangle;
	pointer->oangle = oangle;
}

JNIEXPORT jfloat JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1outvol(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	float result_ = pointer->outvol;
	return (jfloat)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1outvol(JNIEnv *java_env, jclass jcls, jlong jpointer, jfloat joutvol) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	float outvol = (float)joutvol;
	pointer->outvol = outvol;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1vam(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD result_ = pointer->vam;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1vam(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jvam) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD vam = (DWORD)jvam;
	pointer->vam = vam;
}

JNIEXPORT jint JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1get_1priority(JNIEnv *java_env, jclass jcls, jlong jpointer) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD result_ = pointer->priority;
	return (jint)result_;
}

JNIEXPORT void JNICALL Java_jouvieje_bass_structures_StructureJNI_BASS_1SAMPLE_1set_1priority(JNIEnv *java_env, jclass jcls, jlong jpointer, jint jpriority) {
	BASS_SAMPLE *pointer = N2J_CAST(jpointer, BASS_SAMPLE *);
	DWORD priority = (DWORD)jpriority;
	pointer->priority = priority;
}



