/* DO NOT EDIT - AUTOGENERATED */
/**
 * 				NativeBass Project
 *
 * Want to use BASS (www.un4seen.com) in the Java language ? NativeBass is made for you.
 * Copyright @ 2007-2011 Jérôme Jouvie
 *
 * Created on 02 jul. 2007
 * @version file v1.1.1
 * @author Jérôme Jouvie (Jouvieje)
 * @site   http://jerome.jouvie.free.fr/
 * @mail   jerome.jouvie@gmail.com
 * 
 * 
 * INTRODUCTION
 * BASS is an audio library for use in Windows and Mac OSX software.
 * Its purpose is to provide developers with the most powerful and
 * efficient (yet easy to use), sample, stream (MP3, MP2, MP1, OGG, WAV, AIFF,
 * custom generated, and more via add-ons), MOD music (XM, IT, S3M, MOD, MTM, UMX),
 * MO3 music (MP3/OGG compressed MODs),
 * and recording functions. All in a tiny DLL, under 100KB* in size.
 * 
 * BASS official web site :
 * 		http://www.un4seen.com/
 * 
 * 
 * GNU LESSER GENERAL PUBLIC LICENSE
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of the License,
 * or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the
 * Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307 USA 
 */

package jouvieje.bass.structures;

import jouvieje.bass.*;
import jouvieje.bass.exceptions.*;
import jouvieje.bass.callbacks.*;
import jouvieje.bass.*;
import jouvieje.bass.defines.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import java.nio.*;
import jouvieje.bass.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import jouvieje.bass.utils.*;

public class BASS_BFX_BQF extends Pointer {
	/**
	 * Create a view of the <code>Pointer</code> object as a <code>BASS_BFX_BQF</code> object.<br>
	 * This view is valid only if the memory holded by the <code>Pointer</code> holds a BASS_BFX_BQF object.
	 */
	public static BASS_BFX_BQF asBASS_BFX_BQF(Pointer pointer) {
		long address = Pointer.getPointer(pointer);
		if(address == 0) return null;
		return new BASS_BFX_BQF(address);
	}
	/**
	 * Allocate a new <code>BASS_BFX_BQF</code>.<br>
	 * The call <code>isNull()</code> on the object created will return false.<br>
	 * <pre><code>  BASS_BFX_BQF obj = BASS_BFX_BQF.allocate();
	 *  (obj == null) <=> obj.isNull() <=> false
	 * </code></pre>
	 */
	public static BASS_BFX_BQF allocate() {
		final long pointer = StructureJNI.BASS_BFX_BQF_new();
		if(pointer == 0) throw new OutOfMemoryError();
		return new BASS_BFX_BQF(pointer);
	}

	protected BASS_BFX_BQF(long pointer) {
		super(pointer);
	}

	/**
	 * Create an object that holds a null <code>BASS_BFX_BQF</code>.<br>
	 * The call <code>isNull()</code> on the object created will returns true.<br>
	 * <pre><code>  BASS_BFX_BQF obj = new BASS_BFX_BQF();
	 *  (obj == null) <=> false
	 *  obj.isNull() <=> true
	 * </code></pre>
	 * To creates a new <code>BASS_BFX_BQF</code>, use the static "constructor" :
	 * <pre><code>  BASS_BFX_BQF obj = BASS_BFX_BQF.allocate();</code></pre>
	 * @see BASS_BFX_BQF#allocate()
	 */
	public BASS_BFX_BQF() {
		super();
	}

	public void release() {
		if(pointer != 0) {
			StructureJNI.BASS_BFX_BQF_delete(pointer);
		}
		pointer = 0;
	}

	/**
	 * BASS_BFX_BQF_xxx filter types
	 */
	public int getFilter() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.BASS_BFX_BQF_get_lFilter(pointer);
		return javaResult;
	}
	/**
	 * BASS_BFX_BQF_xxx filter types
	 */
	public void setFilter(int filter) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_BQF_set_lFilter(pointer, filter);
	}

	/**
	 * [1Hz..<info.freq/2] Cutoff (central) frequency in Hz
	 */
	public float getCenter() {
		if(pointer == 0) throw new NullPointerException();
		float javaResult = StructureJNI.BASS_BFX_BQF_get_fCenter(pointer);
		return javaResult;
	}
	/**
	 * [1Hz..<info.freq/2] Cutoff (central) frequency in Hz
	 */
	public void setCenter(float center) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_BQF_set_fCenter(pointer, center);
	}

	/**
	 * [-15dB...0...+15dB] Used only for PEAKINGEQ and Shelving filters in dB
	 */
	public float getGain() {
		if(pointer == 0) throw new NullPointerException();
		float javaResult = StructureJNI.BASS_BFX_BQF_get_fGain(pointer);
		return javaResult;
	}
	/**
	 * [-15dB...0...+15dB] Used only for PEAKINGEQ and Shelving filters in dB
	 */
	public void setGain(float gain) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_BQF_set_fGain(pointer, gain);
	}

	/**
	 * [0.1...........<10] Bandwidth in octaves (fQ is not in use (fBandwidth has a priority over fQ))
	 */
	public float getBandwidth() {
		if(pointer == 0) throw new NullPointerException();
		float javaResult = StructureJNI.BASS_BFX_BQF_get_fBandwidth(pointer);
		return javaResult;
	}
	/**
	 * [0.1...........<10] Bandwidth in octaves (fQ is not in use (fBandwidth has a priority over fQ))
	 */
	public void setBandwidth(float bandwidth) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_BQF_set_fBandwidth(pointer, bandwidth);
	}

	/**
	 * [0.1.............1] The EE kinda definition (linear) (if fBandwidth is not in use)
	 */
	public float getQ() {
		if(pointer == 0) throw new NullPointerException();
		float javaResult = StructureJNI.BASS_BFX_BQF_get_fQ(pointer);
		return javaResult;
	}
	/**
	 * [0.1.............1] The EE kinda definition (linear) (if fBandwidth is not in use)
	 */
	public void setQ(float q) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_BQF_set_fQ(pointer, q);
	}

	/**
	 * [0.1.............1] A "shelf slope" parameter (linear) (used only with Shelving filters)
	 */
	public float getS() {
		if(pointer == 0) throw new NullPointerException();
		float javaResult = StructureJNI.BASS_BFX_BQF_get_fS(pointer);
		return javaResult;
	}
	/**
	 * [0.1.............1] A "shelf slope" parameter (linear) (used only with Shelving filters)
	 */
	public void setS(float s) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_BQF_set_fS(pointer, s);
	}

	/**
	 * BASS_BFX_CHANxxx flag/s
	 */
	public int getChannel() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.BASS_BFX_BQF_get_lChannel(pointer);
		return javaResult;
	}
	/**
	 * BASS_BFX_CHANxxx flag/s
	 */
	public void setChannel(int channel) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_BQF_set_lChannel(pointer, channel);
	}

}