/* DO NOT EDIT - AUTOGENERATED */
/**
 * 				NativeBass Project
 *
 * Want to use BASS (www.un4seen.com) in the Java language ? NativeBass is made for you.
 * Copyright @ 2007-2011 Jérôme Jouvie
 *
 * Created on 02 jul. 2007
 * @version file v1.1.1
 * @author Jérôme Jouvie (Jouvieje)
 * @site   http://jerome.jouvie.free.fr/
 * @mail   jerome.jouvie@gmail.com
 * 
 * 
 * INTRODUCTION
 * BASS is an audio library for use in Windows and Mac OSX software.
 * Its purpose is to provide developers with the most powerful and
 * efficient (yet easy to use), sample, stream (MP3, MP2, MP1, OGG, WAV, AIFF,
 * custom generated, and more via add-ons), MOD music (XM, IT, S3M, MOD, MTM, UMX),
 * MO3 music (MP3/OGG compressed MODs),
 * and recording functions. All in a tiny DLL, under 100KB* in size.
 * 
 * BASS official web site :
 * 		http://www.un4seen.com/
 * 
 * 
 * GNU LESSER GENERAL PUBLIC LICENSE
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of the License,
 * or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the
 * Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307 USA 
 */

package jouvieje.bass.structures;

import jouvieje.bass.*;
import jouvieje.bass.exceptions.*;
import jouvieje.bass.callbacks.*;
import jouvieje.bass.*;
import jouvieje.bass.defines.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import java.nio.*;
import jouvieje.bass.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import jouvieje.bass.utils.*;

public class BASS_BFX_PHASER extends Pointer {
	/**
	 * Create a view of the <code>Pointer</code> object as a <code>BASS_BFX_PHASER</code> object.<br>
	 * This view is valid only if the memory holded by the <code>Pointer</code> holds a BASS_BFX_PHASER object.
	 */
	public static BASS_BFX_PHASER asBASS_BFX_PHASER(Pointer pointer) {
		long address = Pointer.getPointer(pointer);
		if(address == 0) return null;
		return new BASS_BFX_PHASER(address);
	}
	/**
	 * Allocate a new <code>BASS_BFX_PHASER</code>.<br>
	 * The call <code>isNull()</code> on the object created will return false.<br>
	 * <pre><code>  BASS_BFX_PHASER obj = BASS_BFX_PHASER.allocate();
	 *  (obj == null) <=> obj.isNull() <=> false
	 * </code></pre>
	 */
	public static BASS_BFX_PHASER allocate() {
		final long pointer = StructureJNI.BASS_BFX_PHASER_new();
		if(pointer == 0) throw new OutOfMemoryError();
		return new BASS_BFX_PHASER(pointer);
	}

	protected BASS_BFX_PHASER(long pointer) {
		super(pointer);
	}

	/**
	 * Create an object that holds a null <code>BASS_BFX_PHASER</code>.<br>
	 * The call <code>isNull()</code> on the object created will returns true.<br>
	 * <pre><code>  BASS_BFX_PHASER obj = new BASS_BFX_PHASER();
	 *  (obj == null) <=> false
	 *  obj.isNull() <=> true
	 * </code></pre>
	 * To creates a new <code>BASS_BFX_PHASER</code>, use the static "constructor" :
	 * <pre><code>  BASS_BFX_PHASER obj = BASS_BFX_PHASER.allocate();</code></pre>
	 * @see BASS_BFX_PHASER#allocate()
	 */
	public BASS_BFX_PHASER() {
		super();
	}

	public void release() {
		if(pointer != 0) {
			StructureJNI.BASS_BFX_PHASER_delete(pointer);
		}
		pointer = 0;
	}

	/**
	 * dry (unaffected) signal mix				[-2......2]
	 */
	public float getDryMix() {
		if(pointer == 0) throw new NullPointerException();
		float javaResult = StructureJNI.BASS_BFX_PHASER_get_fDryMix(pointer);
		return javaResult;
	}
	/**
	 * dry (unaffected) signal mix				[-2......2]
	 */
	public void setDryMix(float dryMix) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_PHASER_set_fDryMix(pointer, dryMix);
	}

	/**
	 * wet (affected) signal mix				[-2......2]
	 */
	public float getWetMix() {
		if(pointer == 0) throw new NullPointerException();
		float javaResult = StructureJNI.BASS_BFX_PHASER_get_fWetMix(pointer);
		return javaResult;
	}
	/**
	 * wet (affected) signal mix				[-2......2]
	 */
	public void setWetMix(float wetMix) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_PHASER_set_fWetMix(pointer, wetMix);
	}

	/**
	 * feedback									[-1......1]
	 */
	public float getFeedback() {
		if(pointer == 0) throw new NullPointerException();
		float javaResult = StructureJNI.BASS_BFX_PHASER_get_fFeedback(pointer);
		return javaResult;
	}
	/**
	 * feedback									[-1......1]
	 */
	public void setFeedback(float feedback) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_PHASER_set_fFeedback(pointer, feedback);
	}

	/**
	 * rate of sweep in cycles per second		[0<....<10]
	 */
	public float getRate() {
		if(pointer == 0) throw new NullPointerException();
		float javaResult = StructureJNI.BASS_BFX_PHASER_get_fRate(pointer);
		return javaResult;
	}
	/**
	 * rate of sweep in cycles per second		[0<....<10]
	 */
	public void setRate(float rate) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_PHASER_set_fRate(pointer, rate);
	}

	/**
	 * sweep range in octaves					[0<....<10]
	 */
	public float getRange() {
		if(pointer == 0) throw new NullPointerException();
		float javaResult = StructureJNI.BASS_BFX_PHASER_get_fRange(pointer);
		return javaResult;
	}
	/**
	 * sweep range in octaves					[0<....<10]
	 */
	public void setRange(float range) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_PHASER_set_fRange(pointer, range);
	}

	/**
	 * base frequency of sweep					[0<...1000]
	 */
	public float getFreq() {
		if(pointer == 0) throw new NullPointerException();
		float javaResult = StructureJNI.BASS_BFX_PHASER_get_fFreq(pointer);
		return javaResult;
	}
	/**
	 * base frequency of sweep					[0<...1000]
	 */
	public void setFreq(float freq) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_PHASER_set_fFreq(pointer, freq);
	}

	/**
	 * BASS_BFX_CHANxxx flag/s
	 */
	public int getChannel() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.BASS_BFX_PHASER_get_lChannel(pointer);
		return javaResult;
	}
	/**
	 * BASS_BFX_CHANxxx flag/s
	 */
	public void setChannel(int channel) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.BASS_BFX_PHASER_set_lChannel(pointer, channel);
	}

}