/* DO NOT EDIT - AUTOGENERATED */
/**
 * 				NativeBass Project
 *
 * Want to use BASS (www.un4seen.com) in the Java language ? NativeBass is made for you.
 * Copyright @ 2007-2011 Jérôme Jouvie
 *
 * Created on 02 jul. 2007
 * @version file v1.1.1
 * @author Jérôme Jouvie (Jouvieje)
 * @site   http://jerome.jouvie.free.fr/
 * @mail   jerome.jouvie@gmail.com
 * 
 * 
 * INTRODUCTION
 * BASS is an audio library for use in Windows and Mac OSX software.
 * Its purpose is to provide developers with the most powerful and
 * efficient (yet easy to use), sample, stream (MP3, MP2, MP1, OGG, WAV, AIFF,
 * custom generated, and more via add-ons), MOD music (XM, IT, S3M, MOD, MTM, UMX),
 * MO3 music (MP3/OGG compressed MODs),
 * and recording functions. All in a tiny DLL, under 100KB* in size.
 * 
 * BASS official web site :
 * 		http://www.un4seen.com/
 * 
 * 
 * GNU LESSER GENERAL PUBLIC LICENSE
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of the License,
 * or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the
 * Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307 USA 
 */

package jouvieje.bass.structures;

import jouvieje.bass.*;
import jouvieje.bass.exceptions.*;
import jouvieje.bass.callbacks.*;
import jouvieje.bass.*;
import jouvieje.bass.defines.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import java.nio.*;
import jouvieje.bass.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import jouvieje.bass.utils.*;

public class TAG_CART_TIMER extends Pointer {
	/**
	 * Create a view of the <code>Pointer</code> object as a <code>TAG_CART_TIMER</code> object.<br>
	 * This view is valid only if the memory holded by the <code>Pointer</code> holds a TAG_CART_TIMER object.
	 */
	public static TAG_CART_TIMER asTAG_CART_TIMER(Pointer pointer) {
		long address = Pointer.getPointer(pointer);
		if(address == 0) return null;
		return new TAG_CART_TIMER(address);
	}
	/**
	 * Allocate and initialize a new <code>TAG_CART_TIMER[]</code>.<br>
	 * @param length length of the array returned.
	 */
	public static TAG_CART_TIMER[] allocate(int length) {
		if(length <= 0) {
			 return null;
		}
		long first = StructureJNI.TAG_CART_TIMER_newArray(length);
		if(first == 0) throw new OutOfMemoryError();
		
		final long sizeOf = StructureJNI.TAG_CART_TIMER_SIZEOF();
		TAG_CART_TIMER[] array = new TAG_CART_TIMER[length];
		for(int i = 0; i < length; i++) {
			array[i] = new TAG_CART_TIMER(first + i * sizeOf);
		}
		return array;
	}

	/**
	 * Allocate a new <code>TAG_CART_TIMER</code>.<br>
	 * The call <code>isNull()</code> on the object created will return false.<br>
	 * <pre><code>  TAG_CART_TIMER obj = TAG_CART_TIMER.allocate();
	 *  (obj == null) <=> obj.isNull() <=> false
	 * </code></pre>
	 */
	public static TAG_CART_TIMER allocate() {
		final long pointer = StructureJNI.TAG_CART_TIMER_new();
		if(pointer == 0) throw new OutOfMemoryError();
		return new TAG_CART_TIMER(pointer);
	}

	protected TAG_CART_TIMER(long pointer) {
		super(pointer);
	}

	/**
	 * Create an object that holds a null <code>TAG_CART_TIMER</code>.<br>
	 * The call <code>isNull()</code> on the object created will returns true.<br>
	 * <pre><code>  TAG_CART_TIMER obj = new TAG_CART_TIMER();
	 *  (obj == null) <=> false
	 *  obj.isNull() <=> true
	 * </code></pre>
	 * To creates a new <code>TAG_CART_TIMER</code>, use the static "constructor" :
	 * <pre><code>  TAG_CART_TIMER obj = TAG_CART_TIMER.allocate();</code></pre>
	 * @see TAG_CART_TIMER#allocate()
	 */
	public TAG_CART_TIMER() {
		super();
	}

	public void release() {
		if(pointer != 0) {
			StructureJNI.TAG_CART_TIMER_delete(pointer);
		}
		pointer = 0;
	}

	/**
	 * FOURCC timer usage ID
	 */
	public int getDwUsage() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.TAG_CART_TIMER_get_dwUsage(pointer);
		return javaResult;
	}
	/**
	 * FOURCC timer usage ID
	 */
	public void setDwUsage(int dwUsage) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_CART_TIMER_set_dwUsage(pointer, dwUsage);
	}

	/**
	 * timer value in samples from head
	 */
	public int getDwValue() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.TAG_CART_TIMER_get_dwValue(pointer);
		return javaResult;
	}
	/**
	 * timer value in samples from head
	 */
	public void setDwValue(int dwValue) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_CART_TIMER_set_dwValue(pointer, dwValue);
	}

}