/* DO NOT EDIT - AUTOGENERATED */
/**
 * 				NativeBass Project
 *
 * Want to use BASS (www.un4seen.com) in the Java language ? NativeBass is made for you.
 * Copyright @ 2007-2011 Jérôme Jouvie
 *
 * Created on 02 jul. 2007
 * @version file v1.1.1
 * @author Jérôme Jouvie (Jouvieje)
 * @site   http://jerome.jouvie.free.fr/
 * @mail   jerome.jouvie@gmail.com
 * 
 * 
 * INTRODUCTION
 * BASS is an audio library for use in Windows and Mac OSX software.
 * Its purpose is to provide developers with the most powerful and
 * efficient (yet easy to use), sample, stream (MP3, MP2, MP1, OGG, WAV, AIFF,
 * custom generated, and more via add-ons), MOD music (XM, IT, S3M, MOD, MTM, UMX),
 * MO3 music (MP3/OGG compressed MODs),
 * and recording functions. All in a tiny DLL, under 100KB* in size.
 * 
 * BASS official web site :
 * 		http://www.un4seen.com/
 * 
 * 
 * GNU LESSER GENERAL PUBLIC LICENSE
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of the License,
 * or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the
 * Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307 USA 
 */

package jouvieje.bass.structures;

import jouvieje.bass.*;
import jouvieje.bass.exceptions.*;
import jouvieje.bass.callbacks.*;
import jouvieje.bass.*;
import jouvieje.bass.defines.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import java.nio.*;
import jouvieje.bass.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import jouvieje.bass.utils.*;

public class TAG_FLAC_CUE_TRACK extends Pointer {
	/**
	 * Create a view of the <code>Pointer</code> object as a <code>TAG_FLAC_CUE_TRACK</code> object.<br>
	 * This view is valid only if the memory holded by the <code>Pointer</code> holds a TAG_FLAC_CUE_TRACK object.
	 */
	public static TAG_FLAC_CUE_TRACK asTAG_FLAC_CUE_TRACK(Pointer pointer) {
		long address = Pointer.getPointer(pointer);
		if(address == 0) return null;
		return new TAG_FLAC_CUE_TRACK(address);
	}
	/**
	 * Allocate a new <code>TAG_FLAC_CUE_TRACK</code>.<br>
	 * The call <code>isNull()</code> on the object created will return false.<br>
	 * <pre><code>  TAG_FLAC_CUE_TRACK obj = TAG_FLAC_CUE_TRACK.allocate();
	 *  (obj == null) <=> obj.isNull() <=> false
	 * </code></pre>
	 */
	public static TAG_FLAC_CUE_TRACK allocate() {
		final long pointer = StructureJNI.TAG_FLAC_CUE_TRACK_new();
		if(pointer == 0) throw new OutOfMemoryError();
		return new TAG_FLAC_CUE_TRACK(pointer);
	}

	protected TAG_FLAC_CUE_TRACK(long pointer) {
		super(pointer);
	}

	/**
	 * Create an object that holds a null <code>TAG_FLAC_CUE_TRACK</code>.<br>
	 * The call <code>isNull()</code> on the object created will returns true.<br>
	 * <pre><code>  TAG_FLAC_CUE_TRACK obj = new TAG_FLAC_CUE_TRACK();
	 *  (obj == null) <=> false
	 *  obj.isNull() <=> true
	 * </code></pre>
	 * To creates a new <code>TAG_FLAC_CUE_TRACK</code>, use the static "constructor" :
	 * <pre><code>  TAG_FLAC_CUE_TRACK obj = TAG_FLAC_CUE_TRACK.allocate();</code></pre>
	 * @see TAG_FLAC_CUE_TRACK#allocate()
	 */
	public TAG_FLAC_CUE_TRACK() {
		super();
	}

	public void release() {
		if(pointer != 0) {
			StructureJNI.TAG_FLAC_CUE_TRACK_delete(pointer);
		}
		pointer = 0;
	}

	/**
	 * track offset (samples)
	 */
	public long getOffset() {
		if(pointer == 0) throw new NullPointerException();
		long javaResult = StructureJNI.TAG_FLAC_CUE_TRACK_get_offset(pointer);
		return javaResult;
	}
	/**
	 * track offset (samples)
	 */
	public void setOffset(long offset) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_CUE_TRACK_set_offset(pointer, offset);
	}

	/**
	 * track number
	 */
	public int getNumber() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.TAG_FLAC_CUE_TRACK_get_number(pointer);
		return javaResult;
	}
	/**
	 * track number
	 */
	public void setNumber(int number) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_CUE_TRACK_set_number(pointer, number);
	}

	/**
	 * ISRC
	 */
	public String getIsrc() {
		if(pointer == 0) throw new NullPointerException();
		String javaResult = StructureJNI.TAG_FLAC_CUE_TRACK_get_isrc(pointer);
		return javaResult;
	}
	/**
	 * ISRC
	 */
	public void setIsrc(String isrc) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_CUE_TRACK_set_isrc(pointer, isrc == null ? null : isrc.getBytes());
	}

	/**
	 * 
	 */
	public int getFlags() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.TAG_FLAC_CUE_TRACK_get_flags(pointer);
		return javaResult;
	}
	/**
	 * 
	 */
	public void setFlags(int flags) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_CUE_TRACK_set_flags(pointer, flags);
	}

	/**
	 * number of indexes
	 */
	public int getNumIndexes() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.TAG_FLAC_CUE_TRACK_get_nindexes(pointer);
		return javaResult;
	}
	/**
	 * number of indexes
	 */
	public void setNumIndexes(int numIndexes) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_CUE_TRACK_set_nindexes(pointer, numIndexes);
	}

	/**
	 * the indexes
	 */
	public TAG_FLAC_CUE_TRACK_INDEX getIndexes() {
		if(pointer == 0) throw new NullPointerException();
		long javaResult = StructureJNI.TAG_FLAC_CUE_TRACK_get_indexes(pointer);
		return javaResult == 0 ? null : TAG_FLAC_CUE_TRACK_INDEX.asTAG_FLAC_CUE_TRACK_INDEX(Pointer.newPointer(javaResult));
	}
	/**
	 * the indexes
	 */
	public void setIndexes(TAG_FLAC_CUE_TRACK_INDEX indexes) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_CUE_TRACK_set_indexes(pointer, Pointer.getPointer(indexes));
	}

}