/* DO NOT EDIT - AUTOGENERATED */
/**
 * 				NativeBass Project
 *
 * Want to use BASS (www.un4seen.com) in the Java language ? NativeBass is made for you.
 * Copyright @ 2007-2011 Jérôme Jouvie
 *
 * Created on 02 jul. 2007
 * @version file v1.1.1
 * @author Jérôme Jouvie (Jouvieje)
 * @site   http://jerome.jouvie.free.fr/
 * @mail   jerome.jouvie@gmail.com
 * 
 * 
 * INTRODUCTION
 * BASS is an audio library for use in Windows and Mac OSX software.
 * Its purpose is to provide developers with the most powerful and
 * efficient (yet easy to use), sample, stream (MP3, MP2, MP1, OGG, WAV, AIFF,
 * custom generated, and more via add-ons), MOD music (XM, IT, S3M, MOD, MTM, UMX),
 * MO3 music (MP3/OGG compressed MODs),
 * and recording functions. All in a tiny DLL, under 100KB* in size.
 * 
 * BASS official web site :
 * 		http://www.un4seen.com/
 * 
 * 
 * GNU LESSER GENERAL PUBLIC LICENSE
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of the License,
 * or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the
 * Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307 USA 
 */

package jouvieje.bass.structures;

import jouvieje.bass.*;
import jouvieje.bass.exceptions.*;
import jouvieje.bass.callbacks.*;
import jouvieje.bass.*;
import jouvieje.bass.defines.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import java.nio.*;
import jouvieje.bass.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import jouvieje.bass.utils.*;

public class TAG_FLAC_PICTURE extends Pointer {
	/**
	 * Create a view of the <code>Pointer</code> object as a <code>TAG_FLAC_PICTURE</code> object.<br>
	 * This view is valid only if the memory holded by the <code>Pointer</code> holds a TAG_FLAC_PICTURE object.
	 */
	public static TAG_FLAC_PICTURE asTAG_FLAC_PICTURE(Pointer pointer) {
		long address = Pointer.getPointer(pointer);
		if(address == 0) return null;
		return new TAG_FLAC_PICTURE(address);
	}
	/**
	 * Allocate a new <code>TAG_FLAC_PICTURE</code>.<br>
	 * The call <code>isNull()</code> on the object created will return false.<br>
	 * <pre><code>  TAG_FLAC_PICTURE obj = TAG_FLAC_PICTURE.allocate();
	 *  (obj == null) <=> obj.isNull() <=> false
	 * </code></pre>
	 */
	public static TAG_FLAC_PICTURE allocate() {
		final long pointer = StructureJNI.TAG_FLAC_PICTURE_new();
		if(pointer == 0) throw new OutOfMemoryError();
		return new TAG_FLAC_PICTURE(pointer);
	}

	protected TAG_FLAC_PICTURE(long pointer) {
		super(pointer);
	}

	/**
	 * Create an object that holds a null <code>TAG_FLAC_PICTURE</code>.<br>
	 * The call <code>isNull()</code> on the object created will returns true.<br>
	 * <pre><code>  TAG_FLAC_PICTURE obj = new TAG_FLAC_PICTURE();
	 *  (obj == null) <=> false
	 *  obj.isNull() <=> true
	 * </code></pre>
	 * To creates a new <code>TAG_FLAC_PICTURE</code>, use the static "constructor" :
	 * <pre><code>  TAG_FLAC_PICTURE obj = TAG_FLAC_PICTURE.allocate();</code></pre>
	 * @see TAG_FLAC_PICTURE#allocate()
	 */
	public TAG_FLAC_PICTURE() {
		super();
	}

	public void release() {
		if(pointer != 0) {
			StructureJNI.TAG_FLAC_PICTURE_delete(pointer);
		}
		pointer = 0;
	}

	/**
	 * ID3v2 "APIC" picture type
	 */
	public int getApic() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.TAG_FLAC_PICTURE_get_apic(pointer);
		return javaResult;
	}
	/**
	 * ID3v2 "APIC" picture type
	 */
	public void setApic(int apic) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_PICTURE_set_apic(pointer, apic);
	}

	/**
	 * mime type
	 */
	public String getMime() {
		if(pointer == 0) throw new NullPointerException();
		String javaResult = StructureJNI.TAG_FLAC_PICTURE_get_mime(pointer);
		return javaResult;
	}
	/**
	 * mime type
	 */
	public void setMime(String mime) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_PICTURE_set_mime(pointer, mime == null ? null : mime.getBytes());
	}

	/**
	 * description
	 */
	public String getDesc() {
		if(pointer == 0) throw new NullPointerException();
		String javaResult = StructureJNI.TAG_FLAC_PICTURE_get_desc(pointer);
		return javaResult;
	}
	/**
	 * description
	 */
	public void setDesc(String desc) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_PICTURE_set_desc(pointer, desc == null ? null : desc.getBytes());
	}

	/**
	 * 
	 */
	public int getWidth() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.TAG_FLAC_PICTURE_get_width(pointer);
		return javaResult;
	}
	/**
	 * 
	 */
	public void setWidth(int width) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_PICTURE_set_width(pointer, width);
	}

	/**
	 * 
	 */
	public int getHeight() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.TAG_FLAC_PICTURE_get_height(pointer);
		return javaResult;
	}
	/**
	 * 
	 */
	public void setHeight(int height) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_PICTURE_set_height(pointer, height);
	}

	/**
	 * 
	 */
	public int getDepth() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.TAG_FLAC_PICTURE_get_depth(pointer);
		return javaResult;
	}
	/**
	 * 
	 */
	public void setDepth(int depth) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_PICTURE_set_depth(pointer, depth);
	}

	/**
	 * 
	 */
	public int getColors() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.TAG_FLAC_PICTURE_get_colors(pointer);
		return javaResult;
	}
	/**
	 * 
	 */
	public void setColors(int colors) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_PICTURE_set_colors(pointer, colors);
	}

	/**
	 * data length
	 */
	public int getLength() {
		if(pointer == 0) throw new NullPointerException();
		int javaResult = StructureJNI.TAG_FLAC_PICTURE_get_length(pointer);
		return javaResult;
	}
	/**
	 * data length
	 */
	public void setLength(int length) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_PICTURE_set_length(pointer, length);
	}

	/**
	 * 
	 */
	public Pointer getData() {
		if(pointer == 0) throw new NullPointerException();
		long javaResult = StructureJNI.TAG_FLAC_PICTURE_get_data(pointer);
		return javaResult == 0 ? null : Pointer.newPointer(javaResult);
	}
	/**
	 * 
	 */
	public void setData(Pointer data) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_FLAC_PICTURE_set_data(pointer, Pointer.getPointer(data));
	}

}