/* DO NOT EDIT - AUTOGENERATED */
/**
 * 				NativeBass Project
 *
 * Want to use BASS (www.un4seen.com) in the Java language ? NativeBass is made for you.
 * Copyright @ 2007-2011 Jérôme Jouvie
 *
 * Created on 02 jul. 2007
 * @version file v1.1.1
 * @author Jérôme Jouvie (Jouvieje)
 * @site   http://jerome.jouvie.free.fr/
 * @mail   jerome.jouvie@gmail.com
 * 
 * 
 * INTRODUCTION
 * BASS is an audio library for use in Windows and Mac OSX software.
 * Its purpose is to provide developers with the most powerful and
 * efficient (yet easy to use), sample, stream (MP3, MP2, MP1, OGG, WAV, AIFF,
 * custom generated, and more via add-ons), MOD music (XM, IT, S3M, MOD, MTM, UMX),
 * MO3 music (MP3/OGG compressed MODs),
 * and recording functions. All in a tiny DLL, under 100KB* in size.
 * 
 * BASS official web site :
 * 		http://www.un4seen.com/
 * 
 * 
 * GNU LESSER GENERAL PUBLIC LICENSE
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of the License,
 * or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the
 * Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307 USA 
 */

package jouvieje.bass.structures;

import jouvieje.bass.*;
import jouvieje.bass.exceptions.*;
import jouvieje.bass.callbacks.*;
import jouvieje.bass.*;
import jouvieje.bass.defines.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import java.nio.*;
import jouvieje.bass.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import jouvieje.bass.utils.*;

public class TAG_ID3 extends Pointer {
	/**
	 * Create a view of the <code>Pointer</code> object as a <code>TAG_ID3</code> object.<br>
	 * This view is valid only if the memory holded by the <code>Pointer</code> holds a TAG_ID3 object.
	 */
	public static TAG_ID3 asTAG_ID3(Pointer pointer) {
		long address = Pointer.getPointer(pointer);
		if(address == 0) return null;
		return new TAG_ID3(address);
	}
	/**
	 * Allocate a new <code>TAG_ID3</code>.<br>
	 * The call <code>isNull()</code> on the object created will return false.<br>
	 * <pre><code>  TAG_ID3 obj = TAG_ID3.allocate();
	 *  (obj == null) <=> obj.isNull() <=> false
	 * </code></pre>
	 */
	public static TAG_ID3 allocate() {
		final long pointer = StructureJNI.TAG_ID3_new();
		if(pointer == 0) throw new OutOfMemoryError();
		return new TAG_ID3(pointer);
	}

	protected TAG_ID3(long pointer) {
		super(pointer);
	}

	/**
	 * Create an object that holds a null <code>TAG_ID3</code>.<br>
	 * The call <code>isNull()</code> on the object created will returns true.<br>
	 * <pre><code>  TAG_ID3 obj = new TAG_ID3();
	 *  (obj == null) <=> false
	 *  obj.isNull() <=> true
	 * </code></pre>
	 * To creates a new <code>TAG_ID3</code>, use the static "constructor" :
	 * <pre><code>  TAG_ID3 obj = TAG_ID3.allocate();</code></pre>
	 * @see TAG_ID3#allocate()
	 */
	public TAG_ID3() {
		super();
	}

	public void release() {
		if(pointer != 0) {
			StructureJNI.TAG_ID3_delete(pointer);
		}
		pointer = 0;
	}

	/**
	 * ID3v1 tag structure
	 */
	public char getId(int elementIndex) {
		if(pointer == 0) throw new NullPointerException();
		if(elementIndex < 0 || elementIndex > 3) throw new IndexOutOfBoundsException(elementIndex+" out of bounds [0; "+3+"[");
		char javaResult = StructureJNI.TAG_ID3_get_id_element(pointer, elementIndex);
		return javaResult;
	}
	/**
	 * ID3v1 tag structure
	 */
	public String getId() {
		if(pointer == 0) throw new NullPointerException();
		String javaResult = StructureJNI.TAG_ID3_get_id(pointer);
		return javaResult;
	}
	/**
	 * ID3v1 tag structure
	 */
	public void setId(int elementIndex, char id) {
		if(pointer == 0) throw new NullPointerException();
		if(elementIndex < 0 || elementIndex > 3) throw new IndexOutOfBoundsException(elementIndex+" out of bounds [0; "+3+"[");
		StructureJNI.TAG_ID3_set_id(pointer, elementIndex, id);
	}

	/**
	 * 
	 */
	public char getTitle(int elementIndex) {
		if(pointer == 0) throw new NullPointerException();
		if(elementIndex < 0 || elementIndex > 30) throw new IndexOutOfBoundsException(elementIndex+" out of bounds [0; "+30+"[");
		char javaResult = StructureJNI.TAG_ID3_get_title_element(pointer, elementIndex);
		return javaResult;
	}
	/**
	 * 
	 */
	public String getTitle() {
		if(pointer == 0) throw new NullPointerException();
		String javaResult = StructureJNI.TAG_ID3_get_title(pointer);
		return javaResult;
	}
	/**
	 * 
	 */
	public void setTitle(int elementIndex, char title) {
		if(pointer == 0) throw new NullPointerException();
		if(elementIndex < 0 || elementIndex > 30) throw new IndexOutOfBoundsException(elementIndex+" out of bounds [0; "+30+"[");
		StructureJNI.TAG_ID3_set_title(pointer, elementIndex, title);
	}

	/**
	 * 
	 */
	public char getArtist(int elementIndex) {
		if(pointer == 0) throw new NullPointerException();
		if(elementIndex < 0 || elementIndex > 30) throw new IndexOutOfBoundsException(elementIndex+" out of bounds [0; "+30+"[");
		char javaResult = StructureJNI.TAG_ID3_get_artist_element(pointer, elementIndex);
		return javaResult;
	}
	/**
	 * 
	 */
	public String getArtist() {
		if(pointer == 0) throw new NullPointerException();
		String javaResult = StructureJNI.TAG_ID3_get_artist(pointer);
		return javaResult;
	}
	/**
	 * 
	 */
	public void setArtist(int elementIndex, char artist) {
		if(pointer == 0) throw new NullPointerException();
		if(elementIndex < 0 || elementIndex > 30) throw new IndexOutOfBoundsException(elementIndex+" out of bounds [0; "+30+"[");
		StructureJNI.TAG_ID3_set_artist(pointer, elementIndex, artist);
	}

	/**
	 * 
	 */
	public char getAlbum(int elementIndex) {
		if(pointer == 0) throw new NullPointerException();
		if(elementIndex < 0 || elementIndex > 30) throw new IndexOutOfBoundsException(elementIndex+" out of bounds [0; "+30+"[");
		char javaResult = StructureJNI.TAG_ID3_get_album_element(pointer, elementIndex);
		return javaResult;
	}
	/**
	 * 
	 */
	public String getAlbum() {
		if(pointer == 0) throw new NullPointerException();
		String javaResult = StructureJNI.TAG_ID3_get_album(pointer);
		return javaResult;
	}
	/**
	 * 
	 */
	public void setAlbum(int elementIndex, char album) {
		if(pointer == 0) throw new NullPointerException();
		if(elementIndex < 0 || elementIndex > 30) throw new IndexOutOfBoundsException(elementIndex+" out of bounds [0; "+30+"[");
		StructureJNI.TAG_ID3_set_album(pointer, elementIndex, album);
	}

	/**
	 * 
	 */
	public char getYear(int elementIndex) {
		if(pointer == 0) throw new NullPointerException();
		if(elementIndex < 0 || elementIndex > 4) throw new IndexOutOfBoundsException(elementIndex+" out of bounds [0; "+4+"[");
		char javaResult = StructureJNI.TAG_ID3_get_year_element(pointer, elementIndex);
		return javaResult;
	}
	/**
	 * 
	 */
	public String getYear() {
		if(pointer == 0) throw new NullPointerException();
		String javaResult = StructureJNI.TAG_ID3_get_year(pointer);
		return javaResult;
	}
	/**
	 * 
	 */
	public void setYear(int elementIndex, char year) {
		if(pointer == 0) throw new NullPointerException();
		if(elementIndex < 0 || elementIndex > 4) throw new IndexOutOfBoundsException(elementIndex+" out of bounds [0; "+4+"[");
		StructureJNI.TAG_ID3_set_year(pointer, elementIndex, year);
	}

	/**
	 * 
	 */
	public char getComment(int elementIndex) {
		if(pointer == 0) throw new NullPointerException();
		if(elementIndex < 0 || elementIndex > 30) throw new IndexOutOfBoundsException(elementIndex+" out of bounds [0; "+30+"[");
		char javaResult = StructureJNI.TAG_ID3_get_comment_element(pointer, elementIndex);
		return javaResult;
	}
	/**
	 * 
	 */
	public String getComment() {
		if(pointer == 0) throw new NullPointerException();
		String javaResult = StructureJNI.TAG_ID3_get_comment(pointer);
		return javaResult;
	}
	/**
	 * 
	 */
	public void setComment(int elementIndex, char comment) {
		if(pointer == 0) throw new NullPointerException();
		if(elementIndex < 0 || elementIndex > 30) throw new IndexOutOfBoundsException(elementIndex+" out of bounds [0; "+30+"[");
		StructureJNI.TAG_ID3_set_comment(pointer, elementIndex, comment);
	}

	/**
	 * 
	 */
	public byte getGenre() {
		if(pointer == 0) throw new NullPointerException();
		byte javaResult = StructureJNI.TAG_ID3_get_genre(pointer);
		return javaResult;
	}
	/**
	 * 
	 */
	public void setGenre(byte genre) {
		if(pointer == 0) throw new NullPointerException();
		StructureJNI.TAG_ID3_set_genre(pointer, genre);
	}

}