/* DO NOT EDIT - AUTOGENERATED */
/**
 * 				NativeBass Project
 *
 * Want to use BASS (www.un4seen.com) in the Java language ? NativeBass is made for you.
 * Copyright @ 2007-2011 Jérôme Jouvie
 *
 * Created on 02 jul. 2007
 * @version file v1.1.1
 * @author Jérôme Jouvie (Jouvieje)
 * @site   http://jerome.jouvie.free.fr/
 * @mail   jerome.jouvie@gmail.com
 * 
 * 
 * INTRODUCTION
 * BASS is an audio library for use in Windows and Mac OSX software.
 * Its purpose is to provide developers with the most powerful and
 * efficient (yet easy to use), sample, stream (MP3, MP2, MP1, OGG, WAV, AIFF,
 * custom generated, and more via add-ons), MOD music (XM, IT, S3M, MOD, MTM, UMX),
 * MO3 music (MP3/OGG compressed MODs),
 * and recording functions. All in a tiny DLL, under 100KB* in size.
 * 
 * BASS official web site :
 * 		http://www.un4seen.com/
 * 
 * 
 * GNU LESSER GENERAL PUBLIC LICENSE
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1 of the License,
 * or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this library; if not, write to the
 * Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330,
 * Boston, MA 02111-1307 USA 
 */

package jouvieje.bass.enumerations;

import jouvieje.bass.*;
import jouvieje.bass.exceptions.*;
import jouvieje.bass.callbacks.*;
import jouvieje.bass.*;
import jouvieje.bass.defines.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import java.nio.*;
import jouvieje.bass.*;
import jouvieje.bass.enumerations.*;
import jouvieje.bass.structures.*;
import jouvieje.bass.utils.*;

class EnumerationJNI {
	static {
		if(!BassInit.isLibrariesLoaded()) {
			throw new RuntimeException("Libraries not loaded, use Init.loadLibraries().");
		}
	}

				/* BASS_ATTRIB */

	protected final static native int get_BASS_ATTRIB_TEMPO_PITCH();
	protected final static native int get_BASS_ATTRIB_TEMPO_FREQ();

				/* BASS_ATTRIB_TEMPO_OPTION */

	protected final static native int get_BASS_ATTRIB_TEMPO_OPTION_AA_FILTER_LENGTH();
	protected final static native int get_BASS_ATTRIB_TEMPO_OPTION_USE_QUICKALGO();
	protected final static native int get_BASS_ATTRIB_TEMPO_OPTION_SEQUENCE_MS();
	protected final static native int get_BASS_ATTRIB_TEMPO_OPTION_SEEKWINDOW_MS();
	protected final static native int get_BASS_ATTRIB_TEMPO_OPTION_OVERLAP_MS();
	protected final static native int get_BASS_ATTRIB_TEMPO_OPTION_PREVENT_CLICK();

				/* BASS_BFX_BQF */

	protected final static native int get_BASS_BFX_BQF_LOWPASS();
	protected final static native int get_BASS_BFX_BQF_HIGHPASS();
	protected final static native int get_BASS_BFX_BQF_BANDPASS();
	protected final static native int get_BASS_BFX_BQF_BANDPASS_Q();
	protected final static native int get_BASS_BFX_BQF_NOTCH();
	protected final static native int get_BASS_BFX_BQF_ALLPASS();
	protected final static native int get_BASS_BFX_BQF_PEAKINGEQ();
	protected final static native int get_BASS_BFX_BQF_LOWSHELF();
	protected final static native int get_BASS_BFX_BQF_HIGHSHELF();

				/* BASS_FX_BFX */

	protected final static native int get_BASS_FX_BFX_ECHO();
	protected final static native int get_BASS_FX_BFX_FLANGER();
	protected final static native int get_BASS_FX_BFX_VOLUME();
	protected final static native int get_BASS_FX_BFX_PEAKEQ();
	protected final static native int get_BASS_FX_BFX_REVERB();
	protected final static native int get_BASS_FX_BFX_LPF();
	protected final static native int get_BASS_FX_BFX_MIX();
	protected final static native int get_BASS_FX_BFX_DAMP();
	protected final static native int get_BASS_FX_BFX_AUTOWAH();
	protected final static native int get_BASS_FX_BFX_ECHO2();
	protected final static native int get_BASS_FX_BFX_PHASER();
	protected final static native int get_BASS_FX_BFX_ECHO3();
	protected final static native int get_BASS_FX_BFX_CHORUS();
	protected final static native int get_BASS_FX_BFX_APF();
	protected final static native int get_BASS_FX_BFX_COMPRESSOR();
	protected final static native int get_BASS_FX_BFX_DISTORTION();
	protected final static native int get_BASS_FX_BFX_COMPRESSOR2();
	protected final static native int get_BASS_FX_BFX_VOLUME_ENV();
	protected final static native int get_BASS_FX_BFX_BQF();

				/* BASS_FX_BPM_TRAN */

	protected final static native int get_BASS_FX_BPM_TRAN_X2();
	protected final static native int get_BASS_FX_BPM_TRAN_2FREQ();
	protected final static native int get_BASS_FX_BPM_TRAN_FREQ2();
	protected final static native int get_BASS_FX_BPM_TRAN_2PERCENT();
	protected final static native int get_BASS_FX_BPM_TRAN_PERCENT2();

				/* EAX_ENVIRONMENT */

	protected final static native int get_EAX_ENVIRONMENT_GENERIC();
	protected final static native int get_EAX_ENVIRONMENT_PADDEDCELL();
	protected final static native int get_EAX_ENVIRONMENT_ROOM();
	protected final static native int get_EAX_ENVIRONMENT_BATHROOM();
	protected final static native int get_EAX_ENVIRONMENT_LIVINGROOM();
	protected final static native int get_EAX_ENVIRONMENT_STONEROOM();
	protected final static native int get_EAX_ENVIRONMENT_AUDITORIUM();
	protected final static native int get_EAX_ENVIRONMENT_CONCERTHALL();
	protected final static native int get_EAX_ENVIRONMENT_CAVE();
	protected final static native int get_EAX_ENVIRONMENT_ARENA();
	protected final static native int get_EAX_ENVIRONMENT_HANGAR();
	protected final static native int get_EAX_ENVIRONMENT_CARPETEDHALLWAY();
	protected final static native int get_EAX_ENVIRONMENT_HALLWAY();
	protected final static native int get_EAX_ENVIRONMENT_STONECORRIDOR();
	protected final static native int get_EAX_ENVIRONMENT_ALLEY();
	protected final static native int get_EAX_ENVIRONMENT_FOREST();
	protected final static native int get_EAX_ENVIRONMENT_CITY();
	protected final static native int get_EAX_ENVIRONMENT_MOUNTAINS();
	protected final static native int get_EAX_ENVIRONMENT_QUARRY();
	protected final static native int get_EAX_ENVIRONMENT_PLAIN();
	protected final static native int get_EAX_ENVIRONMENT_PARKINGLOT();
	protected final static native int get_EAX_ENVIRONMENT_SEWERPIPE();
	protected final static native int get_EAX_ENVIRONMENT_UNDERWATER();
	protected final static native int get_EAX_ENVIRONMENT_DRUGGED();
	protected final static native int get_EAX_ENVIRONMENT_DIZZY();
	protected final static native int get_EAX_ENVIRONMENT_PSYCHOTIC();
	protected final static native int get_EAX_ENVIRONMENT_COUNT();

				/* STREAMPROC_SPECIAL */

	protected final static native int get_STREAMPROC_DUMMY();
	protected final static native int get_STREAMPROC_PUSH();

}